### ISSUE TITLE
Create donation possibility for Open Source Grants and/or the Foundation

### ISSUE THREAD

**Issue by alicetragedy** [travis-ci/travis-foundation#61]
We don't yet have more specific requirements for a donation button, but I've talked several times with @anikalindtner about adding something like that to the Foundation site. 
I will update this ticket with new info and requirements as they come in; maybe donating via stripe (like we have on the RGSoC website) could be a possibility.

**Comment by lislis** [comment]
I have a wip for Stripe checkout here https://github.com/travis-ci/travis-foundation/pull/84

Question is how people notify Foundation about receipts and things like that?
Also I made up all the text, so if you have copy I can put it in there :)

**Comment by alicetragedy** [comment]
I just took a quick look at your PR, and actually I would have suggested that same thing you did, which is to be like, “if you've donated and need a receipt, get in touch with us!”
Regarding copy, I will think about it and get back to you, is that ok? 
Thanks so much for this @lislis 😻

**Comment by lislis** [comment]
@alicetragedy I'm basically done with the stripe integration (side from testing it in the actual true live environment:tm:) 
I created a new app which is called `foundation-stripe-backend` under travis-pro and on heroku. This app processes the charge through Stripe and is already live. I'll write up some documentation in the builders manual runbooks.

One thing though: We need to migrate the foundation page from gh-pages over to heroku to get ssl.
I pretty much have everything in place, the new home on heroku will be https://travis-foundation-website.herokuapp.com (and the donate page https://travis-foundation-website.herokuapp.com/donate). There are two things left to do:
- [ ] change DNS so that foundation.travis-ci.com routes to heroku and not to gh-pages
- [ ] setup autodeploy for passing master on Travis. This way, if you merge a PR and it passed, it automatically deploys to heroku. So it feels like the old gh-pages workflow (takes a bit longer but also has the html-proofer step)

**Comment by lislis** [comment]
PR for runbook https://github.com/travis-pro/manual/pull/485

**Comment by lislis** [comment]
Also (so that I don't forget)
- [ ] review copy
- [ ] client side feedback (also error messages that are not just console logs)

**Comment by alicetragedy** [comment]
Is there anything you want me to look at already (besides copy)? Should I review the documentation? Maybe we can set up a time slot to do some of this together if you need me or if there's anything you want to show me — realistically earliest would be next week for me (and for you as well, I think).
Thanks in advance, I'm super excited about this ✨

**Comment by lislis** [comment]
@alicetragedy scheduling a date would probably be the best, either early morning or late at night in case I 💥 things :D I'll try and finish/ prepare outstanding tasks by Friday. Maybe Monday morning or evening would be a good idea?

**Comment by alicetragedy** [comment]
@lislis my Monday is already pretty full but you can take a look at my availability (evening I could do 7pm CET?) — otherwise Tuesday evening from like 16:30 on works! Just send me a cal invite <3

**Comment by alicetragedy** [comment]
this has been done — thanks again @lislis for the help! ❤️
